### PR TITLE
T9 f2 17

### PR DESCRIPTION
**Pull request by mitchneides**
Hey guys, once we merge Gino's Dao into S2 please give this a look.
In addition to scanning the code let's also all do our individual postman test tickets with this code before approving it so we can move this along (note that we'll all have to individually add the controller to the server in order to be able to test, but then delete that line after so we don't create conflicts because it's Kyle's ticket to actually put it in the server and then merge into S2).

Let me know once you've reviewed the code/tested if there are any issues or if good to merge

### CODE REVIEW

**Comment by Romangino** [comment]
Needed to update GroupDao to fix userCreatesGroup:
- https://github.com/Romangino/software-engineering-project-node/pull/13

Postman Tests Collection: 
- https://www.getpostman.com/collections/e332596ad8dea48dce50

**Comment by Romangino** [comment]
I've updated T9F2-17 with the latest updates merged into S2, like the GroupDao. I will create another PR to this ticket with the updated GroupDao

**Comment by spencerbelsky** [comment]
Looks good

**Comment by Romangino** [comment]
Updates merged in. Looks good

**Pull request merged**
