### PR TITLE
Fix userCreateGroup in GroupDao.ts

### PR DESCRIPTION
**Pull request by Romangino**
Allows user to add members and admins to body as well as add the user creating the group to members and admins

Added GroupController to server.ts for testing

### CODE REVIEW

**Comment by adityaputtigampala** [comment]
These updates look good to merge in

**Comment by mitchneides** [comment]
I'm testing userCreatesGroup right now and it's mostly working but seems to be adding the creator into the members array twice. Anyone else seeing this? (Testing locally at the moment so haven't tried with the atlas db but I assume it'll be the same)

**Comment by Romangino** [comment]
> I'm testing userCreatesGroup right now and it's mostly working but seems to be adding the creator into the members array twice. Anyone else seeing this? (Testing locally at the moment so haven't tried with the atlas db but I assume it'll be the same)

Are you adding the creator to body?

**Comment by mitchneides** [comment]
> 

Yeah like this:

{
    "members": ["633c41de89045f21193ea004", "633c421b89045f21193ea008"],
    "createdOn": "11-22-2022",
    "admin": ["633c41de89045f21193ea004"],
    "groupName": "AliceCharlie",
    "description": "Alice and Charlie makin plans"
}

Were you automatically adding the creator and therefore we shouldn't pass them in as a member upon creation?

**Comment by mitchneides** [comment]
Also 1 more thing - can we change findGroupByName in group Dao to ignore the case?
As in - if the group name is "Alice-Bob" we should be able to retrieve it even if we type "alice-bob"

(Won't let me comment in line since this code was already committed)

**Comment by Romangino** [comment]
Yea so since we're passing in uid and group I thought we wouldn't be adding the creator to members or admin. If everything was going to be in the body including the creator added to members and admin then we wouldn't need uid parameter

**Comment by mitchneides** [comment]
Other than those 2 things I've tested all the functionality with postman tests and everything looks good on my end.
So once we get those sorted I'm good to merge both Gino's and my PRs

**Comment by mitchneides** [comment]
"Yea so since we're passing in uid and group I thought we wouldn't be adding the creator to members or admin. If everything was going to be in the body including the creator added to members and admin then we wouldn't need uid parameter"

Got it ok I'll stop adding them into the body on create then.
So yeah then just the ignore case thing (if you guys agree?) and then I think we're good

**Comment by Romangino** [comment]
Made it able to search case-insensitive

**Comment by spencerbelsky** [comment]
Looks good

**Pull request merged**
